Added main structure(index.html/style.css)
braincee/Portfolio-Webstie pull request #1
Opened 2022-03-16 16:55 UTC by braincee

2022-03-18 00:21 UTC, uche-inyama requested changes
Hi @braincee  :wave: 

Good job so far! your project is coming along just fine.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] In your next commit, add a bit touch to the messages - more description, when writing them :slightly_smiling_face: 

_Check the comments under the review._

## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 00:21 UTC, uche-inyama commented on index.html
> +               <li><img src="images/hamburger.png" alt="hamburger-icon" class="hamburger"></li>
Kindly wrap your hamburger button implementation, inside a `<nav>` tag. :slightly_smiling_face:

2022-03-18 00:21 UTC, uche-inyama commented on README.md
> +Github: https://github.com/braincee
Kindly add the missing headers in your readme file. Use this [template for reference](https://github.com/microverseinc/readme-template/blob/master/README.md)

[**optional**] For headers that might be redundant, kindly leave them out, for example, **Install and Run Test**.

2022-03-18 00:56 UTC, braincee commented on index.html
> +               <li><img src="images/hamburger.png" alt="hamburger-icon" class="hamburger"></li>
Please Mr Henry, You just reviewed my code and said I should make changes in the hamburger nav tag. I have a screenshot of the issue. The hamburger is already in a nav tag. Please should I remove it and put it into another nav tag. 
Like this:  <nav>
  <img src="images/hamburger.png" alt="hamburger-icon" class="hamburger">
</nav>
Waiting patiently for reply, Thanks

2022-03-18 10:31 UTC, prolajumokeoni approved these changes
Hi  @braincee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider inline comments in the review


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 10:31 UTC, prolajumokeoni commented on README.md
> +LinkedIn: https://www.linkedin.com/in/kwesi-appiah-1387801a1/
## OPTIONAL

- [ ] Kindly use this formats to make your links readable and more professional, check [microverse templates](https://github.com/microverseinc/readme-template/blob/master/README.md), you can fork it so you can always use it 👍🏿 

`GitHub: [@githubhandle](https://github.com/githubhandle)
Twitter: [@twitterhandle](https://twitter.com/twitterhandle)
LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)`

2022-03-18 10:31 UTC, prolajumokeoni commented on index.html
> +           <a href="#">LOGO</a>
- [ ] Kindly use the same font color used in the figma design for your logo, please check screenshot below  👍🏿

2022-03-18 10:31 UTC, prolajumokeoni commented on index.html
> +            <h3 class="tech">SOFTWARE DEVELOPER</h3>
## OPTIONAL

- [ ] Kindly use the same color for the h2 tag just like the Figma design, you can make this a h1 tag so it serves as the heading of your website 👍🏿 
- [ ] Kindly make the h3 tag be on one line
- [ ] Kindly add the background image for this section 👍🏿 

 Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![AA](https://user-images.githubusercontent.com/69638013/158986583-e8f2e44f-7ceb-43ae-8547-44ec3b3adffe.png)  |  ![SD](https://user-images.githubusercontent.com/69638013/158986630-4c5d5735-486f-4fc5-b930-3b9ba35f918e.png)

2022-03-18 10:31 UTC, prolajumokeoni commented on index.html
> +               <li class="bars"><i class="fa-solid fa-bars"></i></li>
## OPTIONAL

- [ ] Kindly increase the size of the hamburger menu icon, please make it look like the Figma design check screenshot below 👍🏿

2022-03-18 23:36 UTC, merged

2022-11-28 00:45 UTC, braincee commented
Thanks very much @prolajumokeoni 
Note: I have implemented all the optional suggestions made by you 

![thank-you](https://user-images.githubusercontent.com/78104544/204169520-cf1ba1d5-5db9-423a-bf41-50e43bb0bcde.gif)