Add style on the contact form
braincee/Portfolio-Webstie pull request #4
Opened 2022-03-22 14:51 UTC by haroldmud

- Resize the contact form title and icons
- Adjust the text block
- Add a box-shadow hover effect on the submission button

2022-03-22 15:25 UTC, ShadyShawkat requested changes
## Hi @haroldmud, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Kindly edit your readme to look more professional, you can use git syntax for styling which is used in [this](https://github.com/microverseinc/readme-template) readme template provided by Microverse. (You can see its 'raw' text to see how the text is displayed like [this](https://raw.githubusercontent.com/microverseinc/readme-template/master/README.md))
- [ ] _Check the comments under the review for more changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 15:25 UTC, ShadyShawkat commented on index.html
> +                </form>
- [ ] Kindly include the 'See Project' button in the form. This button is supposed to be the submit button of this form.

2022-03-22 15:25 UTC, ShadyShawkat commented on index.html
> +                </h1>
- [ ] Please change this `h1` tag to any other heading tag `t2`-`t6`. Your web page should contain only one `h1` tag for the main title of the page and then other heading tags depending on the hierarchy of the headings.

2022-03-22 19:44 UTC, prolajumokeoni approved these changes
Hi @braincee  and @haroldmud, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 19:56 UTC, merged

2022-11-28 00:54 UTC, braincee commented
Thanks very much, @ShadyShawkat and @prolajumokeoni 

Note: I have implemented all the reviews and optional changes required

![thank-you](https://user-images.githubusercontent.com/78104544/204170159-3ca38bb5-996f-49a9-817d-79f20d5dcd70.gif)