Add desktop version using media queries
braincee/Portfolio-Webstie pull request #5
Opened 2022-03-23 10:05 UTC by braincee

I added a desktop version to my portfolio website making it responsive on all devices.

2022-03-23 14:11 UTC, micheaol requested changes
Hi @braincee , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-23 14:11 UTC, micheaol commented on style.css
> +  .title-4 {
Please ensure that your media queries for the Desktop breakpoint in the CSS file. (the value for `min-width` property should be in range of `992px` - `1100px`)

2022-03-24 11:24 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @braincee,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 11:26 UTC, merged

2022-11-28 00:57 UTC, braincee commented
Thanks very much, @micheaol and @TedLivist 

Note: I have implemented all the review and optional changes required

![thank-you-thanks](https://user-images.githubusercontent.com/78104544/204170371-ce24c79f-f052-43cd-a2e2-d96371e343db.gif)